services:
  - type: web
    name:
    env: node
    plan: free
    buildCommand: npm install && npm run build && npx prisma:generate
    startCommand: node dist/server.js
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: CORS_ORIGIN
        sync: false
